name: neefs
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  #4 state management
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  either_dart: ^0.4.0
  equatable: ^2.0.5
    
  #request
  dio: ^5.1.2

  #routing
  go_router: ^7.0.1

  #local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^8.0.0

  #service locator
  get_it: ^7.6.0
  
  #connectivity check
  connectivity_plus: ^4.0.1

  #etc
  flex_color_scheme: ^7.1.0
  flutter_easyloading: ^3.0.5
  carousel_slider: ^4.2.1
  html: ^0.15.3
  flutter_slidable: ^3.0.0
  flutter_localization: ^0.1.11
  shared_preferences: ^2.1.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.4
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/reis.jpg
    - assets/lang/
