name: neefs
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #4 state management
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  either_dart: ^0.4.0
  equatable: ^2.0.5
  
  #routing
  go_router: ^7.0.1

  #local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  #request
  dio: ^5.1.2

  #etc
  flex_color_scheme: ^7.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
